apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: agent
  name: agent
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: agent
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/copilot-default: "true"
        io.kompose.service: agent
    spec:
      containers:
        - args:
            - python3
            - bot/bot.py
          image: 100.125.7.25:20202/linkando/bot:latest
          name: agent-container
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
