name: Build and Push image

on:
  push:
    branches: [ "azure_image" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure YML file
      run: |
        tg_token_line='telegram_token: "${{ secrets.TG_BOT_TOKEN }}"'
        openai_key_line='openai_api_key: "${{ secrets.OPENAI_API_KEY }}"'
        sed -i'.bak' "1s/.*/$tg_token_line/" config/config.example.yml
        sed -i'.bak' "2s/.*/$openai_key_line/" config/config.example.yml

    - name: Rename Configuration Files
      run: |
        mv config/config.example.yml config/config.yml
        mv config/config.example.env config/config.env

    - name: Build Docker Compose
      run: docker compose --env-file config/config.env build

    - name: Push Docker Image to Repository
      run: |
        docker login -u $REGISTRY_USER -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY_SERVER
        docker tag chatgpt_telegram_bot:latest $REGISTRY_SERVER/chatgpt_telegram_bot:latest
        docker push $REGISTRY_SERVER/chatgpt_telegram_bot:latest
